### PR TITLE
Allow for showing internal topics from the empty state when no topics exist

### LINKED ISSUE #672: Topic listing missing search header when only internal topics present
When only internal topics are present in a Kafka cluster, there is no way to view the internal topics that may be present.

image

### PR DESCRIPTION
**Pull request by riccardo-forina**
Fixes #672

## Storybook stories
image
image

## In app changes
image
image

### CODE REVIEW

**Review by MikeEdgar — APPROVED** [review]

**Comment by shirimordechay** [comment]
Looks good, just a couple of comments:

1. Is there a reason why we call them "Hidden" instead of "Internal" topics in the secondary button? we should be consistent with the terminology we use.  
2. As a usability enhancement, I suggest we include a link to Docs where users can learn more about Creating topics (below the buttons as [PF guidelines](https://www.patternfly.org/components/empty-state/design-guidelines#elements) show)

**Comment by hemahg** [comment]
I have added an external link to the create topic docs, @shirimordechay and @riccardo-forina please let me know if you have any naming suggestions for an external link

Attaching the screenshot for storybook stories
Screenshot 2024-05-22 at 10 41 42 PM
Screenshot 2024-05-22 at 10 42 12 PM

**Comment by shirimordechay** [comment]
@hemahg Looks good to me. about the naming of the external text, we can use the same header as it shown in the docs "Configuring Kafka topics". 

Also, make sure to add it in the docs and copy the spreadsheet (See https://docs.google.com/spreadsheets/d/1R7sX5cSAxzbu87uHNolBfa9EF31YD8n3Z3WpsFirAWU/edit#gid=0)

**Comment by hemahg** [comment]
@shirimordechay, I have updated the PR as per the review comment. update the doc as well but I don't have permission to update the spreadsheet

**Review by shirimordechay — APPROVED** [review]

**Pull request merged**
